### ISSUE TITLE
Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [qingxiang-jia/intro-to-java#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. The posts in this repository linked below contains solutions to our Space Needle homework assignment:

https://github.com/qingxiang-jia/intro-to-java/blob/master/lab05/SpaceNeedle.java
https://github.com/qingxiang-jia/intro-to-java/blob/master/lab05/SpaceNeedle.java~

These posts' solution code is indexed by Google, enabling current students to easily find them and cheat on their assignments.

Would you please remove these posts from your repository or make them private in order to help us enforce our academic policy?

By removing these posts, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu

More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by qingxiang-jia** [comment]
Hi Jonathan, sorry about that, I will delete this repository as other schools may have similar issues.
